services:
  - type: web
    name: ai-smartphone-advisor
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ai_phone_advisor.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DJANGO_SETTINGS_MODULE
        value: ai_phone_advisor.settings