# Generated by Django 6.0.3 on 2026-03-31 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ram', models.IntegerField(help_text='GB hisobida')),
                ('storage', models.IntegerField(help_text='GB hisobida')),
                ('antutu_score', models.IntegerField(blank=True, null=True)),
                ('camera_mp', models.IntegerField(help_text='Asosiy kamera megapikseli')),
                ('battery_capacity', models.IntegerField(help_text='mAh')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
            ],
        ),
    ]
