# Generated by Django 6.0.3 on 2026-04-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phones/'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
