# Generated by Django 6.0.3 on 2026-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_smartphone_image_smartphone_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_mp',
            field=models.CharField(help_text='Masalan: 50MP + 12MP + 10MP', max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='description',
            field=models.TextField(blank=True, help_text='AI tomonidan berilgan ekspert tahlili'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(help_text='Masalan: 8/12/16 GB', max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='storage',
            field=models.CharField(help_text='Masalan: 128/256/512 GB yoki 1TB', max_length=50),
        ),
    ]
