# Generated by Django 6.0.3 on 2026-04-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_brand_name_alter_smartphone_camera_mp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='price',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='body_material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='cpu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='global_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='gpu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='old_camera',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='special_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='user_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='uzb_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='antutu_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_mp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='storage',
            field=models.CharField(max_length=100),
        ),
    ]
