# Generated by Django 6.0.3 on 2026-04-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_smartphone_image_remove_smartphone_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPriceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.FloatField()),
                ('usage_goal', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('gpu', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('antutu_score', models.IntegerField(blank=True, null=True)),
                ('global_price', models.FloatField()),
                ('ai_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
