# Generated by Django 6.0.3 on 2026-04-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_aipricerecommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aipricerecommendation',
            old_name='ai_reason',
            new_name='description',
        ),
        migrations.AddField(
            model_name='aipricerecommendation',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aipricerecommendation',
            name='global_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
