# Generated by Django 6.0.3 on 2026-04-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_ai_reason_aipricerecommendation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='global_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='uzb_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
