# Generated by Django 6.0.3 on 2026-04-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_smartphone_global_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='body_material',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_mp',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='cpu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='global_price',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='gpu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='model_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='old_camera',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='storage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='uzb_price',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
