# Generated by Django 6.0.3 on 2026-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_smartphone_body_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
