# Generated by Django 6.0.3 on 2026-04-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('camera', models.TextField()),
                ('video', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('antutu', models.CharField(max_length=50)),
                ('battery', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_comment', models.TextField()),
            ],
        ),
    ]
