# Generated by Django 6.0.3 on 2026-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingSmartphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='Rasm URL manzili')),
                ('antutu_v11_score', models.IntegerField(verbose_name='AnTuTu v11 Real Vaqt Balli')),
                ('brand', models.CharField(max_length=50, verbose_name='Brend')),
                ('device_model', models.CharField(max_length=100, verbose_name='Smartfon Modeli')),
                ('cpu', models.CharField(max_length=100, verbose_name='Protsessor (CPU)')),
                ('gpu', models.CharField(max_length=100, verbose_name='Video tezlatgich (GPU)')),
                ('camera', models.CharField(max_length=255, verbose_name='Kamera xususiyatlari')),
                ('body_material', models.CharField(max_length=255, verbose_name='Korpus va Material')),
                ('additional_features', models.TextField(verbose_name="Qo'shimcha Imkoniyatlar")),
                ('segment', models.CharField(choices=[('hardcore', 'Hardcore Gaming (Mutlaq Yetakchilar)'), ('flagship', 'Flagship (Yuqori Unumdor Flagmanlar)'), ('premium', 'Premium & Foldable (Buklanuvchan va Premium)'), ('value', 'Value for Money (Narx/Sifat nisbati)')], max_length=50, verbose_name='Smartfon Segmenti')),
                ('ai_summary', models.TextField(verbose_name='AI Xulosasi (Tahlil)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Bazaga qo'shilgan vaqt")),
            ],
            options={
                'verbose_name': 'Gaming Smartphone',
                'verbose_name_plural': 'Gaming Smartphones',
                'ordering': ['-antutu_v11_score'],
            },
        ),
    ]
