# Generated by Django 6.0.3 on 2026-04-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_gamingsmartphones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraphone',
            options={'ordering': ['camera_rank']},
        ),
        migrations.AddField(
            model_name='cameraphone',
            name='camera_rank',
            field=models.PositiveIntegerField(default=0, help_text="Kamera sifati bo'yicha o'rni (1 - eng zo'ri)"),
        ),
    ]
