# Generated by Django 6.0.3 on 2026-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_cameraphone_options_cameraphone_camera_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(unique=True)),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('antutu_score', models.IntegerField()),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('camera', models.TextField(blank=True, null=True)),
                ('battery', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_comment', models.TextField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, help_text='Foydalanuvchilar fikri', null=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
